In [ ]:
import matplotlib as mpl
from matplotlib import pyplot as plt

In [ ]:
help(mpl)

In [5]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import regularizers
import tensorflow as tf

In [4]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import confusion_matrix,classification_report

In [11]:
dir(regularizers)

['L1',
 'L1L2',
 'L2',
 'OrthogonalRegularizer',
 'Regularizer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'deserialize',
 'get',
 'l1',
 'l1_l2',
 'l2',
 'orthogonal_regularizer',
 'serialize']

In [12]:
a=((2,4),(3,9))

In [13]:
(a1,b1),(a2,b2)=a

In [14]:
print(a1,b1,a2,b2)

2 4 3 9


In [15]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [16]:
x_train.shape

(60000, 28, 28)

In [17]:
x_train[0].shape

(28, 28)

In [18]:
plt.imshow(x_train[0],cmap='gray')
print("label:",y_train[0])

label: 5


In [19]:
print(x_train[2].shape)

(28, 28)


In [20]:
x_train[2]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,  67, 232,  39,   0,   0,   0,
          0,   0],
       [  

In [26]:
x_train=x_train/255
x_test=x_test/255

In [27]:
print(x_train[2].shape)

(784,)


In [28]:
x_train[2]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [21]:
from tensorflow.keras.layers import Flatten

In [31]:
a b
c d
a b c d

SyntaxError: invalid syntax (1758648882.py, line 1)

In [35]:
model=Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(100,activation='relu'))
model.add(Dense(300,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [36]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 100)               78500     
                                                                 
 dense_1 (Dense)             (None, 300)               30300     
                                                                 
 dense_2 (Dense)             (None, 500)               150500    
                                                                 
 dense_3 (Dense)             (None, 10)                5010      
                                                                 
Total params: 264,310
Trainable params: 264,310
Non-trainable params: 0
_________________________________________________________________


In [8]:
model=Sequential([
Flatten(input_shape=(28,28)),
#Dense(512,activation='relu',input_shape=(784,)),
Dense(512,activation='relu'),
Dense(128,activation='tanh'),
Dense(10,activation='softmax')
                ])

In [9]:
model.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 128)               65664     
                                                                 
 dense_2 (Dense)             (None, 10)                1290      
                                                                 
Total params: 468,874
Trainable params: 468,874
Non-trainable params: 0
_________________________________________________________________


In [11]:
#print(y_train[4])

In [76]:
#yyy=to_categorical(y_train[4])

In [77]:
#print(yyy)

In [12]:
PATH='./check/checkpoint.h5'

In [79]:
#mycallback=[
#keras.callbacks.EarlyStopping(monitor='val_accuracy',patience=2,mode='max'),
#keras.callbacks.Model.Checkpoint(filepath=PATH,monitor='val_accuracy',save_best_only=True,mode='max')
#]

In [13]:
#to_categorical(y_test).shape

In [22]:
history = model.fit(
 x_train,    
 y_train,
 epochs=10,
 batch_size=64,
 validation_split=0.1,
 shuffle=True
 #,
 #callbacks=mycallback
)

Epoch 1/10
844/844 [==============================] - 5s 4ms/step - loss: 0.7752 - accuracy: 0.7674 - val_loss: 0.5120 - val_accuracy: 0.8557
Epoch 2/10
844/844 [==============================] - 3s 4ms/step - loss: 0.5481 - accuracy: 0.8313 - val_loss: 0.4879 - val_accuracy: 0.8448
Epoch 3/10
844/844 [==============================] - 3s 4ms/step - loss: 0.4862 - accuracy: 0.8485 - val_loss: 0.4484 - val_accuracy: 0.8692
Epoch 4/10
844/844 [==============================] - 3s 4ms/step - loss: 0.5107 - accuracy: 0.8455 - val_loss: 0.4275 - val_accuracy: 0.8725
Epoch 5/10
844/844 [==============================] - 3s 4ms/step - loss: 0.4911 - accuracy: 0.8483 - val_loss: 0.3644 - val_accuracy: 0.8855
Epoch 6/10
844/844 [==============================] - 3s 4ms/step - loss: 0.4457 - accuracy: 0.8612 - val_loss: 0.3486 - val_accuracy: 0.8880
Epoch 7/10
844/844 [==============================] - 3s 4ms/step - loss: 0.4563 - accuracy: 0.8623 - val_loss: 0.4882 - val_accuracy: 0.8552
Epoch 

In [23]:
model.save('/content/drive/MyDrive/ML with Tensorflow/Week2_Linear regression and artificial neural network/saved_model.h5')

In [24]:
eval=model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.4600 - accuracy: 0.8599


In [25]:
print(eval)

[0.45998531579971313, 0.8598999977111816]


In [26]:
history.history

{'loss': [0.7752110958099365,
  0.5481008887290955,
  0.48619991540908813,
  0.5107226371765137,
  0.4911474585533142,
  0.4456837773323059,
  0.4562961161136627,
  0.5111225247383118,
  0.4729936718940735,
  0.4646874666213989],
 'accuracy': [0.7674259543418884,
  0.8312963247299194,
  0.8484629392623901,
  0.8455185294151306,
  0.8483333587646484,
  0.8611851930618286,
  0.862333357334137,
  0.8422407507896423,
  0.8544999957084656,
  0.8584444522857666],
 'val_loss': [0.5119930505752563,
  0.48794063925743103,
  0.44839754700660706,
  0.4275025725364685,
  0.3644082546234131,
  0.34859269857406616,
  0.4881696403026581,
  0.46265697479248047,
  0.37148088216781616,
  0.40303942561149597],
 'val_accuracy': [0.8556666374206543,
  0.8448333144187927,
  0.8691666722297668,
  0.8725000023841858,
  0.8855000138282776,
  0.8880000114440918,
  0.8551666736602783,
  0.8560000061988831,
  0.8889999985694885,
  0.8796666860580444]}

In [29]:
plt.plot(history.history['loss'],color='red')
plt.plot(history.history['val_loss'],color='orange')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.ylim([0,.2])
plt.legend(['Loss','Val_loss'])
plt.show





<function matplotlib.pyplot.show(close=None, block=None)>

In [30]:
plt.plot(history.history['accuracy'],color='green')
plt.plot(history.history['val_accuracy'],color='blue')
plt.ylabel('acc')
plt.xlabel('epoch')
plt.ylim([0.8,1])
plt.legend(['Acc','Val_Acc'])
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

In [32]:
plt.imshow(x_test[1].reshape(28,28),cmap='gray')
print("label: ",y_test[1])

label:  2


In [33]:
pred=model.predict(x_test[1].reshape(1,28,28))


1/1 [==============================] - 0s 354ms/step


In [34]:
tf.argmax(pred,axis=-1).numpy()[0]

2

In [35]:
print(pred*10)

[[1.7976586e-04 5.6316651e-04 7.2708249e+00 2.7029943e+00 1.9110434e-05
  4.1798688e-04 2.1883773e-02 1.0946207e-05 3.1032241e-03 2.8516706e-06]]


In [36]:
prediction=model.predict(x_test[8].reshape(1,784))

1/1 [==============================] - 0s 72ms/step


In [37]:
prediction

array([[2.1482203e-03, 6.7500796e-06, 2.1165457e-04, 3.2433165e-06,
        2.6672158e-01, 1.5455984e-01, 2.2418149e-01, 3.8046041e-06,
        3.4850991e-01, 3.6534916e-03]], dtype=float32)

In [38]:
pred=tf.argmax(prediction,axis=-1).numpy()

In [39]:
print(pred[0])

8


In [40]:
plt.imshow(x_test[8].reshape(28,28),cmap='gray')
print("label:",y_test[8])

label: 5


In [41]:
from tensorflow.keras.preprocessing.image import load_img,img_to_array

In [43]:
img=load_img('/content/drive/MyDrive/ML with Tensorflow/Week2_Linear regression and artificial neuaral network/two.jpg',color_mode="grayscale",target_size=(28,28),interpolation="nearest")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/ML with Tensorflow/Week2_Linear regression and artificial neuaral network/two.jpg'